### PR TITLE
Fix issue relating to terraform v0.12.0 release

### LINKED ISSUE #15: Issue with attributes for ansible group
I have the following being reported in my terminal:

```
ANSIBLE_TF_WS_NAME=staging ./terraform-inventory.py 
Traceback (most recent call last):
  File "./terraform-inventory.py", line 400, in _main
    inventory.add_resource(resource)
  File "./terraform-inventory.py", line 243, in add_resource
    self.add_group_resource(resource)
  File "./terraform-inventory.py", line 216, in add_group_resource
    groupname = resource.read_attr("inventory_group_name")
  File "./terraform-inventory.py", line 184, in read_attr
    return self._raw_attributes().get(key, None)
  File "./terraform-inventory.py", line 189, in _raw_attributes
    return self.source_json["attributes"]
KeyError: 'attributes'
```

This is using a 'remote' terraform backend, Terraform v0.12.0. The state says it is version 4. Here's an example of the state:

```
{
  "version": 4,
  "terraform_version": "0.12.0",
  "serial": 2,
  "lineage": "1a478ae2-6647-8ebd-0815-46b948b7b22e",
  "outputs": {
    "infra_vpn_static_ip": {
      "value": "139.59.203.99",
      "type": "string"
    }
  },
  "resources": [
    {
      "mode": "managed",
      "type": "ansible_group",
      "name": "database",
      "provider": "provider.ansible",
      "instances": [
        {
          "schema_version": 0,
          "attributes_flat": {
            "id": "database",
            "inventory_group_name": "database"
          }
        }
      ]
    }
}
```

I can see 'attributes_flat' but not 'attributes'. I've tried changing a value here and there to see if it worked, but I'm not a python dev so I can't see how the data is structured at line 189 to see what the key should be.

I'll keep digging though.

### PR DESCRIPTION
**Pull request by designermonkey**
Fixes #15

### CODE REVIEW

**Comment by nbering** [comment]
I'll look at this in the evening after my work day is complete. I would just like to run the tests and make sure this doesn't break anything.

**Comment by nbering** [comment]
It seems this breaks the tests for the test cases I've recorded for Terraform 0.12.x, based on the pre-release versions.

```
~/git/nbering/terraform-inventory [issue-15-patch L|✔]
23:34 $ bin/debug /Users/nicholasbering/git/nbering/terraform-inventory/sample_data/0.12.x/count-advanced
Traceback (most recent call last):
  File "/Users/nicholasbering/git/nbering/terraform-inventory/terraform.py", line 393, in _main
    inventory.add_resource(resource)
  File "/Users/nicholasbering/git/nbering/terraform-inventory/terraform.py", line 235, in add_resource
    self.add_host_resource(resource)
  File "/Users/nicholasbering/git/nbering/terraform-inventory/terraform.py", line 199, in add_host_resource
    hostname = resource.read_attr("inventory_hostname")
  File "/Users/nicholasbering/git/nbering/terraform-inventory/terraform.py", line 178, in read_attr
    return self._raw_attributes().get(key, None)
  File "/Users/nicholasbering/git/nbering/terraform-inventory/terraform.py", line 183, in _raw_attributes
    return self.source_json["attributes_flat"]
KeyError: 'attributes_flat'
```
To run the tests yourself, use the scripts under `bin/run-tests`, which will run all of the tests. A pass is a return code 0 with no output. A fail will say `TEST FAILED: /path/to/test-case`.

The tests simply diff the script output to a known good result and fail if it's not a match. It uses `jq` to sort the keys in the result so that the output doesn't have to be finicky, and the script sorts lists of hosts so that there shouldn't be any variability in results for the same state input.

Use `bin/debug /path/to/test-case` to get a side-by-side diff for the case you're having trouble with. The test doesn't run Terraform, it's using a shim to fake terraform and just spit out the recorded state file when it's called with the right arguments.

If you add or update a test case and want to record a new expects.json with the results to be compared, there's a helper at `bin/update-expects` which runs all the scenarios and records their results as a the new expected result.

**Comment by nbering** [comment]
I think I'd like to continue to support the beta statefile format, at least until I know that they aren't going to flip back again. I would probably approach this by renaming the test case folder for 0.12.x to 0.12.0-beta, copy them to a new 0.12.x, and init the new test case "projects" with 0.12.1 to get a representative sample across recent versions.

I'd be happy to help out solving this, but I usually work on this project over the weekend, so it'll be a few days before I can look at it.

**Comment by jmMeessen** [comment]
Hello,

As time has passed and that Terraform 0.12 got some more stability, what is the status of this PR?

/- Jmm

**Comment by nbering** [comment]
@jmMeessen Great question. I'll try and carve out some time to check on the stability of this project against more recent versions. As it stands, this PR is stalled as basic testing failed and the PR author never responded to my comments about that.

**Comment by patsevanton** [comment]
Hello, Thanks for terraform-inventory.

Terraform 0.13 released. May be merge PR?

**Comment by nbering** [comment]
@patsevanton Thanks for bringing this again PR to my attention. I think I'm just going to close this, as the issue it's solving (#15) is also closed. I was never able to replicate the original issue. If anyone still has this problem... I could use some help figuring out what the difference in structure of the state file is... and why yours is different from the baselines I've seen elsewhere.

**Pull request closed without merging**
