### PR TITLE
Aspect/tf workspace

### PR DESCRIPTION
**Pull request by dnitsch**
Extended for TF workspace

### CODE REVIEW

**Comment by nbering** [comment]
I'd like to test it out before merging, but it looks pretty good.

**Comment by nbering** [comment]
I'm requesting a review from myself to remind me to look at this when I get a minute.

**Comment by dnitsch** [comment]
Great thanks @nbering, I was going to include a test - if I get time I'll add a `test_terraform.py` now that I have the fork :).

**Comment by nbering** [comment]
I had a chance to play around with the changes. Seems to work as intended. Thanks for the PR!

**Review by nbering — APPROVED** [review]
Seems to work as intended and existing cases work fine. Thanks! 🏆

**Pull request merged**
